easy_admin:
    site_name: 'Kat'
    formats:
        time: 'h:i:s'
    entities:
        Article:
            class: App\Entity\Article
            list:
                fields:
                    - { property: 'Titre'}
                    - { property: 'SousTitre'}
                    - { property: 'Texte'}
                    - { property: 'image', type: 'image', base_path: 'imagesArticles' }
                    - { property: 'Date' }
            form:
                fields:
                    - { property: 'Titre'}
                    - { property: 'SousTitre'}
                    - { property: 'Texte', type: 'fos_ckeditor'}
                    - { property: 'imageFile', type: 'file', base_path: 'imagesArticles' }
                    - { property: 'Date' }
        Music:
            class: App\Entity\Music
            list:
                fields:
                    - { property: 'Titre'}
            form:
                fields:
                    - { property: 'Embed'}
                    - { property: 'Titre'}
        Envent:
            class: App\Entity\Event
            list:
                fields:
                    - { property: 'Date', type: 'date'}
                    - { property: 'Horaire' }
                    - { property: 'Lieu'}
                    - { property: 'Titre' }
                    - { property: 'Presentation' }
                    - { property: 'Info'}
                    - { property: 'Billeterie'}
            form:
                fields:
                    - { property: 'Date', type: 'date'}
                    - { property: 'Horaire', type: 'time' }
                    - { property: 'Lieu'}
                    - { property: 'Titre' }
                    - { property: 'Presentation' }
                    - { property: 'Info'}
                    - { property: 'Billeterie'}
    design:
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

