vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix: '%kernel.project_dir%/public/imagesArticles'
            upload_destination: '%kernel.project_dir%/public/imagesArticles'
